export const data = [
  {
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    mobile_no: "123-456-7890",
    job_title: "Software Engineer",
    company_name: "Tech Corp",
    address: "123 Tech St.",
    city: "Tech City",
    state: "Tech State",
    zip_code: "12345",
    country: "Countryland",
    status: "Active",
    lifecycle_stage: "Lead",
    source: "Web",
    medium: "Organic",
    replyCount: 10,
    RFQ: 3,
    Positive: 5,
    Negative: 2,
    Neutral: 3,
    facebook_username: "john_doe_fb",
    twitter_username: "john_doe_tw",
    linkedin_username: "john_doe_in",
    sales_owner: "Jane Smith",
    team_id: "Team A",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  {
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    mobile_no: "987-654-3210",
    job_title: "Marketing Manager",
    company_name: "Business Inc.",
    address: "456 Business Ave.",
    city: "Business Town",
    state: "Biz State",
    zip_code: "67890",
    country: "Countryland",
    status: "Inactive",
    lifecycle_stage: "Customer",
    source: "Email",
    medium: "Paid",
    replyCount: 20,
    RFQ: 5,
    Positive: 12,
    Negative: 3,
    Neutral: 5,
    facebook_username: "jane_smith_fb",
    twitter_username: "jane_smith_tw",
    linkedin_username: "jane_smith_in",
    sales_owner: "Mike Johnson",
    team_id: "Team B",
  },
  // Add more sample data as needed
];
